version: '3'
services:
  wordpress:
    # Build from Dockerfile in the ./wordpress folder
    build: ./wordpress
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql
    volumes:
      - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql:3306
    env_file:
      - wordpress.env
    # logging:
    #   driver: "gcplogs"
    restart: always

  mysql:
    image: mysql:latest
    volumes:
       - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
    env_file:
      - wordpress.env

volumes:
  db_data: {}
  wp_data: {}
